/**
 * Tests for the generated/minified file detector. This module silently
 * skips whole files, so a false positive here blinds the scanner — the
 * old bare /webpack/i marker skipped ANY file that mentioned a bundler
 * in its first 500 characters, including real source files.
 */

import { isGeneratedFile } from '../generatedFileDetector';

describe('isGeneratedFile — path heuristics', () => {
  it.each([
    '/repo/dist/app.js',
    '/repo/build/main.js',
    '/repo/src/__generated__/schema.ts',
    '/repo/src/api.generated.ts',
    '/repo/vendor/lib.js',
    '/repo/app.min.js',
    '/repo/app.bundle.js',
  ])('skips %s', (p) => {
    expect(isGeneratedFile(p, 'const x = 1;\n')).toBe(true);
  });

  it.each([
    '/repo/src/app.js',
    '/repo/src/builder.ts',
    '/repo/src/distance.py',
  ])('keeps %s', (p) => {
    expect(isGeneratedFile(p, 'const x = 1;\n')).toBe(false);
  });
});

describe('isGeneratedFile — content markers', () => {
  it('skips files with explicit generation banners', () => {
    expect(isGeneratedFile('/r/x.ts', '/* @generated by protoc */\nconst a = 1;\n')).toBe(true);
    expect(isGeneratedFile('/r/x.ts', '// DO NOT EDIT — automatically generated\nconst a = 1;\n')).toBe(true);
  });

  it('skips real webpack bundle output', () => {
    expect(isGeneratedFile('/r/x.js', '/******/ (function(modules) { // webpackBootstrap\n')).toBe(true);
    expect(isGeneratedFile('/r/x.js', 'var m = __webpack_require__(42);\n')).toBe(true);
  });

  it('does NOT skip source files that merely mention a bundler', () => {
    expect(isGeneratedFile('/r/webpack.config.js', "const webpack = require('webpack');\nmodule.exports = {};\n")).toBe(false);
    expect(isGeneratedFile('/r/build.ts', "import { rollup } from 'rollup';\nexport const cfg = 1;\n")).toBe(false);
    expect(isGeneratedFile('/r/notes.ts', '// we use parcel for bundling\nexport const a = 1;\n')).toBe(false);
  });

  it('skips minified single-line content', () => {
    const minified = 'var a=1;'.repeat(200); // 1600 chars, no newlines
    expect(isGeneratedFile('/r/x.js', minified)).toBe(true);
  });

  it('keeps ordinary multi-line source', () => {
    const source = Array(50).fill('const value = compute(1, 2);').join('\n');
    expect(isGeneratedFile('/r/x.js', source)).toBe(false);
  });
});
