#!/usr/bin/env node
/**
 * Bundle the Claude Code plugin hooks.
 *
 * Each hook in src/hooks/ is bundled (engine included) into a single
 * self-contained JS file under plugin/hooks/. The bundles are COMMITTED:
 * `/plugin install <git-url>` clones the repo as-is with no build step,
 * so the plugin must work straight from a checkout. Re-run this script
 * (npm run build:plugin) after any change to src/hooks/, src/rules/, or
 * the engine, and commit the result.
 *
 * Bundling also keeps the hooks fast: one file, no node_modules
 * resolution, no npx — a cold `node plugin/hooks/post-write-scan.js` is
 * just node boot + one require.
 */

const esbuild = require('esbuild');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const ENTRIES = {
  'pre-write-guard': 'src/hooks/preWriteGuard.ts',
  'post-write-scan': 'src/hooks/postWriteScan.ts',
  'stop-gate': 'src/hooks/stopGate.ts',
};

for (const [outName, entry] of Object.entries(ENTRIES)) {
  esbuild.buildSync({
    entryPoints: [path.join(ROOT, entry)],
    bundle: true,
    platform: 'node',
    target: 'node18',
    outfile: path.join(ROOT, 'plugin', 'hooks', `${outName}.js`),
    // Not minified: these artifacts are committed and should be reviewable.
    minify: false,
    banner: {
      js: '#!/usr/bin/env node\n// Generated by `npm run build:plugin` — do not edit; edit src/hooks/ and re-run.',
    },
    logLevel: 'warning',
  });
  process.stdout.write(`bundled plugin/hooks/${outName}.js\n`);
}
